name: Publish NuGet

on:
  release:
    types: [published]

jobs:
  publish:
    name: build, pack & publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4

      - name: publish on version change
        id: publish_nuget
        uses: alirezanet/publish-nuget@v3.0.4
        with:
          PROJECT_FILE_PATH: Net.Bluewalk.DotNetUtils/Net.Bluewalk.DotNetUtils.csproj
          NUGET_KEY: ${{ secrets.NUGET_API_KEY }}
          DOTNET_CLI_TELEMETRY_OPTOUT: 1
          DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
